# Generated by Django 5.0.3 on 2024-03-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=10)),
            ],
        ),
    ]
